// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAndp2O4MiGElzE5w2wwbdY223o3l-Mj_A',
    appId: '1:444989182641:web:b7db31db8a551afdd6c890',
    messagingSenderId: '444989182641',
    projectId: 'formfillpro',
    authDomain: 'formfillpro.firebaseapp.com',
    databaseURL: 'https://formfillpro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'formfillpro.appspot.com',
    measurementId: 'G-JBQQLB8S3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbHrVrYvjyv7t_889tNPhK67xQsTWOao',
    appId: '1:444989182641:android:2b3dca3ddaf995ead6c890',
    messagingSenderId: '444989182641',
    projectId: 'formfillpro',
    databaseURL: 'https://formfillpro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'formfillpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDremEnrVtKmZnhoGEpfhHNecST5NgY33I',
    appId: '1:444989182641:ios:e317cf6acbff3fa7d6c890',
    messagingSenderId: '444989182641',
    projectId: 'formfillpro',
    databaseURL: 'https://formfillpro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'formfillpro.appspot.com',
    iosBundleId: 'com.example.formfillpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDremEnrVtKmZnhoGEpfhHNecST5NgY33I',
    appId: '1:444989182641:ios:cce99492497f5c32d6c890',
    messagingSenderId: '444989182641',
    projectId: 'formfillpro',
    databaseURL: 'https://formfillpro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'formfillpro.appspot.com',
    iosBundleId: 'com.example.formfillpro.RunnerTests',
  );
}
